apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-minio
  namespace: gitlab
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`minio.local.{{ base_domain }}`)
    kind: Rule
    services:
    - name: gitlab-minio-svc
      port: 9000
