certmanager:
  install: false
gitlab:
  gitlab-shell:
    maxReplicas: 1
    minReplicas: 1
  migrations:
    enabled: true
  sidekiq:
    cluster: false
    maxReplicas: 1
    minReplicas: 1
{% if gitlab_backup_enabled %}
  task-runner:
    backups:
      cron:
        enabled: true
        schedule: {{ gitlab_backup_schedule }}
{% endif %}
  webservice:
    ingress:
      enabled: false
    maxReplicas: 1
    minReplicas: 1
gitlab-runner:
  install: false
global:
{% if gitlab_sso_enabled %}
  appConfig:
    omniauth:
      allowSingleSignOn:
      - saml
      autoLinkSamlUser: true
      autoSignInWithProvider: saml
      blockAutoCreatedUsers: false
      enabled: true
      providers:
      - secret: saml-sso
{% endif %}
  edition: ce
{% if gitlab_mail_enabled %}
  email:
    display_name: GitLab@{{ base_domain }}
    from: {{ gitlab_mail_from }}
    reply_to: {{ gitlab_mail_from }}
    subject_suffix: null
{% endif %}
  grafana:
    enabled: false
  hosts:
    domain: {{ base_domain }}
    gitlab:
      name: git.{{ base_domain }}
    minio:
      name: minio.local.{{ base_domain }}
    registry:
      name: hub.{{ base_domain }}
  ingress:
    configureCertmanager: false
    enabled: false
    tls:
      enabled: false
{% if gitlab_mail_enabled %}
  smtp:
    address: {{ gitlab_mail_smtp }}
    authentication: login
    enabled: true
    openssl_verify_mode: peer
    password:
      key: password
      secret: gitlab-mail-password
    port: {{ gitlab_mail_smtp_port }}
    starttls_auto: true
    user_name: {{ gitlab_mail_from }}
{% endif %}
nginx-ingress:
  enabled: false
prometheus:
  install: false
registry:
  ingress:
    enabled: false
  hpa:
    maxReplicas: 1
    minReplicas: 1
minio:
  ingress:
    enabled: false
