apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-webservice
  namespace: gitlab
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`git.{{ base_domain }}`)
    kind: Rule
    services:
    - name: gitlab-webservice
      port: 8181
  - match: Host(`git.{{ base_domain }}`) && Path(`/admin/sidekiq`)
    kind: Rule
    services:
    - name: gitlab-webservice
      port: 8080
