apiVersion: v1
stringData:
  provider: |
    {
        "name": "saml",
        "args": {
            "assertion_consumer_service_url": "{{ gitlab_sso_assertion_consumer_service_url }}",
            "idp_cert": "-----BEGIN CERTIFICATE-----\n{{ gitlab_sso_idp_cert }}\n-----END CERTIFICATE-----\n",
            "idp_sso_target_url": "{{ gitlab_sso_idp_url }}",
            "idp_slo_target_url": "{{ gitlab_sso_idp_url }}",
            "certificate": "-----BEGIN CERTIFICATE-----\n{{ gitlab_sso_certificate }}\n-----END CERTIFICATE-----\n",
            "private_key": "-----BEGIN RSA PRIVATE KEY-----\n{{ gitlab_sso_private_key }}\n-----BEGIN RSA PRIVATE KEY-----\n",
            "issuer": "{{ gitlab_sso_issuer }}",
            "name_identifier_format": "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
            "security": {
                "authn_requests_signed": true,
                "want_assertions_signed": true,
                "embed_sign": true,
                "metadata_signed": true,
                "signature_method": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
                "digest_method": "http://www.w3.org/2001/04/xmlenc#sha256"
            }
        },
        "label": "{{ gitlab_sso_name }}"
    }
kind: Secret
metadata:
  name: saml-sso
  namespace: gitlab
type: Opaque
