apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-registry
  namespace: gitlab
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`hub.{{ base_domain }}`)
    kind: Rule
    services:
    - name: gitlab-registry
      port: 5000
