---
- name: Create namespace velero
  community.kubernetes.k8s:
    name: velero
    api_version: v1
    kind: Namespace
    state: present

- name: Add vmware-tanzu chart repo
  community.kubernetes.helm_repository:
    name: vmware-tanzu
    repo_url: https://vmware-tanzu.github.io/helm-charts

- name: Install helm chart velero
  community.kubernetes.helm:
    name: velero
    chart_ref: vmware-tanzu/velero
    chart_version: 2.12.0
    release_namespace: velero
    values: "{{ lookup('template', 'velero-values.yaml') | from_yaml }}"

- name: Create velero servicemonitor
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'velero-servicemonitor.yaml') }}"

- name: Create velero-backup prometheusrule
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'velero-backup-prometheusrule.yaml') }}"
