existingSecret: minio-backup-credentials
persistence:
  storageClass: backup
{% if buckets is defined %}
buckets:
{% for bucket in buckets %}
  - name: {{ bucket }}
    policy: none
    purge: false
{% endfor %}
{% endif %}
