---
- name: Create minio-backup namespace
  community.kubernetes.k8s:
    name: minio-backup
    api_version: v1
    kind: Namespace
    state: present

- name: Add stable chart repo
  community.kubernetes.helm_repository:
    name: stable
    repo_url: https://kubernetes-charts.storage.googleapis.com

- name: Create minio-backup credentials secret
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'minio-backup-credentials-secret.yaml') }}"

- name: Install helm chart minio-backup
  community.kubernetes.helm:
    name: minio-backup
    chart_ref: stable/minio
    chart_version: 5.0.26
    release_namespace: minio-backup
    values: "{{ lookup('template', 'minio-backup-values.yaml') | from_yaml }}"

- name: Create minio-backup ingressroute
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'minio-backup-ingressroute.yaml') }}"
