apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus-operator
    app: prometheus-operator
  name: argocd-app-sync-status
  namespace: monitoring
spec:
  groups:
  - name: general.rules
    rules:
    - alert: argocd-app-sync-status
      annotations:
        description: Argo CD app not synced
        summary: Argo CD app sync status
      expr: argocd_app_info{sync_status!="Synced"}
      labels:
        severity: critical
