apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus-operator
    app: prometheus-operator
  name: argocd-app-health
  namespace: monitoring
spec:
  groups:
  - name: general.rules
    rules:
    - alert: argocd-app-health
      annotations:
        description: Argo CD app health not healthy
        summary: Argo CD app health
      expr: argocd_app_info{health_status!="Healthy"}
      labels:
        severity: critical
