---
# roles/traefik
cf_api_key: # API Key for Cloudflare

# roles/minio-backup
secretkey: # Minio secret key

# roles/stash
restic_password: # Password for backups in restic repository

# roles/prometheus-operator
slack_url: https://hooks.slack.com/services/ # Slack url for alertmanager notifications
grafana_sso_client_secret: # Keycloak OIDC client secret for grafana

# roles/gitlab
gitlab_sso_idp_cert: # Keycloak IDP cert
gitlab_sso_certificate: # Keycloak SAML cert
gitlab_sso_private_key: # Keycloak SAML private key
gitlab_mail_password: # SMTP password for mail delivery

# roles/argocd
argocd_sso_client_secret: # Keycloak OIDC client secret for argocd
