apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik-config.yaml: |
    http:
{% if routers is defined %}
      routers:
{% for router in routers %}
        {{ router.name }}:
          entryPoints:
{% for entrypoint in router.entrypoints %}
            - {{ entrypoint }}
{% endfor %}
          rule: "{{ router.rule }}"
{% if router.middlewares is defined %}
          middlewares:
{% for middleware in router.middlewares %}
            - {{ middleware }}
{% endfor %}
{% endif %}
          service: {{ router.service }}
{% endfor %}
{% endif %}
      middlewares:
        headers-default:
          headers:
            sslRedirect: true
            browserXssFilter: true
            contentTypeNosniff: true
            forceSTSHeader: true
            stsIncludeSubdomains: true
            stsPreload: true
            stsSeconds: 15552000
            customFrameOptionsValue: SAMEORIGIN
{% if services is defined %}
      services:
{% for service in services %}
        {{ service.name }}:
          loadBalancer:
            servers:
{% for server in service.servers %}
              - url: "{{ server }}"
{% endfor %}
            passHostHeader: true
{% endfor %}
{% endif %}
