apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus-operator
    app: prometheus-operator
  name: stash-backup
  namespace: monitoring
spec:
  groups:
  - name: general.rules
    rules:
    - alert: stash-backup
      annotations:
        description: Stash backup failure
        summary: Stash backup
      expr: stash_backup_host_backup_success != 1
      labels:
        severity: critical
