---
- name: Create Cloudflare API Secret
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'cloudflare-api-credentials-secret.yaml') }}"
  notify: Restart Traefik

- name: Create Traefik configmap
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'traefik-config-configmap.yaml') }}"
  notify: Restart Traefik

- name: Add Traefik chart repo
  community.kubernetes.helm_repository:
    name: traefik
    repo_url: https://containous.github.io/traefik-helm-chart

- name: Install helm chart Traefik
  community.kubernetes.helm:
    name: traefik
    chart_ref: traefik/traefik
    chart_version: 8.2.1
    release_namespace: kube-system
    values: "{{ lookup('template', 'traefik-values.yaml') | from_yaml }}"

- name: Create Traefik dashboard ingressroute
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'traefik-dashboard-ingressroute.yaml') }}"

- name: Create addprefix pihole middleware
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'addprefix-pihole-middleware.yaml') }}"
