---
- name: Clone local-path-provisioner repo
  git:
    repo: https://github.com/rancher/local-path-provisioner
    dest: /tmp/local-path-provisioner

- name: Create local-path-provisioner namespace
  community.kubernetes.k8s:
    name: local-path-provisioner
    api_version: v1
    kind: Namespace
    state: present

- name: Install helm chart ssd local-path-provisioner
  community.kubernetes.helm:
    name: ssd
    chart_ref: /tmp/local-path-provisioner/deploy/chart
    release_namespace: local-path-provisioner
    values: "{{ lookup('template', 'ssd-local-path-provisioner-values.yaml') | from_yaml }}"

- name: Install helm chart hdd local-path-provisioner
  community.kubernetes.helm:
    name: hdd
    chart_ref: /tmp/local-path-provisioner/deploy/chart
    release_namespace: local-path-provisioner
    values: "{{ lookup('template', 'hdd-local-path-provisioner-values.yaml') | from_yaml }}"
